#!/usr/bin/env sh

SOURCE_FILE="$1"
FLAVOR="$2"  # light/dark
DESTINATION_PATH="$3"

SOURCE_FILENAME="$(basename "$SOURCE_FILE")"
SOURCE_FILENAME_SANITIZED="$(sed -e "s/ /_/g" <<<"$SOURCE_FILENAME")"
OUTPUT_FILENAME="$SOURCE_FILENAME_SANITIZED.theme"

cp "$SOURCE_FILE" "$DESTINATION_PATH/$OUTPUT_FILENAME"
